version: '3.3'
volumes:
  db_data: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
services:
  prime-multiplication-table-php:
    container_name: prime-multiplication-table-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ~/.composer:/home/taste/.composer
    expose:
      - "9000"
    environment:
      MYSQL_ROOT_PASSWORD: r34llys3cur3Passw0rdr00t
      MYSQL_DATABASE: prime-multiplication
      MYSQL_USER: prime-multiplication
      MYSQL_PASSWORD: r34llys3cur3Passw0rd
  prime-multiplication-table-db:
    container_name: prime-multiplication-table-db
    image: mysql:8.2.0
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r34llys3cur3Passw0rdr00t
      MYSQL_DATABASE: prime-multiplication
      MYSQL_USER: prime-multiplication
      MYSQL_PASSWORD: r34llys3cur3Passw0rd

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
