version: '3.3'
volumes:
  db_data: {}
services:
  prime-multiplication-table-php:
    container_name: prime-multiplication-table-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ~/.composer:/home/taste/.composer
    expose:
      - "9000"
    environment:
      MYSQL_ROOT_PASSWORD: r34llys3cur3Passw0rdr00t
      MYSQL_DATABASE: prime-multiplication
      MYSQL_USER: prime-multiplication
      MYSQL_PASSWORD: r34llys3cur3Passw0rd
  prime-multiplication-table-db:
    container_name: prime-multiplication-table-db
    image: mysql:8.2.0
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r34llys3cur3Passw0rdr00t
      MYSQL_DATABASE: prime-multiplication
      MYSQL_USER: prime-multiplication
      MYSQL_PASSWORD: r34llys3cur3Passw0rd
